src/hello_world/config/routes.rb
HelloWorld::Application.routes.draw do 
  resources :faculcies

  resources :subjects

  resources :marks

  resources :students

  root :to => 'home#index'

end

src/hello_world/app/models/faculcy.rb
class Faculcy < ActiveRecord::Base
  attr_accessible :title

  validates_presence_of :title

  has_many :students , :inverse_of => :faculcy
end

src/hello_world/app/controllers/faculcies_controller.rb
class FaculciesController < ApplicationController
  # GET /faculcies
  # GET /faculcies.json
  def index
    @faculcies = Faculcy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faculcies }
    end
  end

  # GET /faculcies/1
  # GET /faculcies/1.json
  def show
    @faculcy = Faculcy.find(params[:id])
    @students = @faculcy.students

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @faculcy }
    end
  end

  # GET /faculcies/new
  # GET /faculcies/new.json
  def new
    @faculcy = Faculcy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @faculcy }
    end
  end

  # GET /faculcies/1/edit
  def edit
    @faculcy = Faculcy.find(params[:id])
  end

  # POST /faculcies
  # POST /faculcies.json
  def create
    @faculcy = Faculcy.new(params[:faculcy])

    respond_to do |format|
      if @faculcy.save
        format.html { redirect_to @faculcy, notice: 'Faculcy was successfully created.' }
        format.json { render json: @faculcy, status: :created, location: @faculcy }
      else
        format.html { render action: "new" }
        format.json { render json: @faculcy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /faculcies/1
  # PUT /faculcies/1.json
  def update
    @faculcy = Faculcy.find(params[:id])

    respond_to do |format|
      if @faculcy.update_attributes(params[:faculcy])
        format.html { redirect_to @faculcy, notice: 'Faculcy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @faculcy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculcies/1
  # DELETE /faculcies/1.json
  def destroy
    @faculcy = Faculcy.find(params[:id])
    @faculcy.destroy

    respond_to do |format|
      format.html { redirect_to faculcies_url }
      format.json { head :no_content }
    end
  end
end

src/hello_world/app/helpers/faculcies_helper.rb
module FaculciesHelper
end

src/hello_world/app/views/faculcies/_form.html.erb
<%= form_for(@faculcy) do |f| %>
  <% if @faculcy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faculcy.errors.count, "error") %> prohibited this faculcy from being saved:</h2>

      <ul>
      <% @faculcy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/hello_world/app/views/faculcies/edit.html.erb
<h1>Editing faculcy</h1>

<%= render 'form' %>

<%= link_to 'Show', @faculcy %> |
<%= link_to 'Back', faculcies_path %>

src/hello_world/app/views/faculcies/index.html.erb
<h1>Listing faculcies</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @faculcies.each do |faculcy| %>
  <tr>
    <td><%= faculcy.title %></td>
    <td><%= link_to 'Show', faculcy %></td>
    <td><%= link_to 'Edit', edit_faculcy_path(faculcy) %></td>
    <td><%= link_to 'Destroy', faculcy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Faculcy', new_faculcy_path %>
<%= link_to 'Back' , root_path %>

src/hello_world/app/views/faculcies/new.html.erb
<h1>New faculcy</h1>

<%= render 'form' %>

<%= link_to 'Back', faculcies_path %>

src/hello_world/app/views/faculcies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @faculcy.title %>
</p>

<p> 
  <b>Students on this faculcy:</b>
  <% if @students.count == 0 %>
    <b> None </b>
  <% else %>
    <br>
    <% @students.each do |st| %>
      <table>
    	<tr>
          <td> <%= st.name + ' ' + st.surname %></td>
          <td><%= link_to 'Show details' , st %></td>
        </tr>
      </table>
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_faculcy_path(@faculcy) %> |
<%= link_to 'Back', faculcies_path %>