src/hello_world/config/routes.rb
HelloWorld::Application.routes.draw do 
  resources :faculcies

  resources :subjects

  resources :marks

  resources :students

  root :to => 'home#index'

end

src/hello_world/app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :title

  validates_presence_of :title

  has_many :marks , :inverse_of => :subject
end

src/hello_world/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subjects }
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @subject = Subject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/new
  # GET /subjects/new.json
  def new
    @subject = Subject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subject }
    end
  end

  # GET /subjects/1/edit
  def edit
    @subject = Subject.find(params[:id])
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(params[:subject])

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render json: @subject, status: :created, location: @subject }
      else
        format.html { render action: "new" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subjects/1
  # PUT /subjects/1.json
  def update
    @subject = Subject.find(params[:id])

    respond_to do |format|
      if @subject.update_attributes(params[:subject])
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url }
      format.json { head :no_content }
    end
  end
end

src/hello_world/app/helpers/subjects_helper.rb
module SubjectsHelper
end

src/hello_world/app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/hello_world/app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

src/hello_world/app/views/subjects/index.html.erb
<h1>Listing subjects</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= subject.title %></td>
    <td><%= link_to 'Show', subject %></td>
    <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
    <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subject', new_subject_path %>
<%= link_to 'Back' , root_path %>

src/hello_world/app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

src/hello_world/app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @subject.title %>
</p>


<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>