src/hello_world/config/routes.rb
HelloWorld::Application.routes.draw do 
  resources :faculcies

  resources :subjects

  resources :marks

  resources :students

  root :to => 'home#index'

end

src/hello_world/app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name, :surname
  validates_presence_of :name
  validates_presence_of :surname

  has_many :marks , :inverse_of => :student 
  belongs_to :faculcy , :inverse_of => :students
end

src/hello_world/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])
    @faculcy = @student.faculcy
    @marks = @student.marks
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

src/hello_world/app/helpers/students_helper.rb
module StudentsHelper
end

src/hello_world/app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/hello_world/app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

src/hello_world/app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Surname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.surname %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>
<%= link_to 'Back' , root_path %>

src/hello_world/app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

src/hello_world/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Surname:</b>
  <%= @student.surname %>
</p>

<p>
  <b>Faculcy:</b>
  <% if @faculcy != nil %>
    <%= link_to @faculcy.title , @faculcy %>
  <% else %>
    <u>NOT assigned to any faculcy'</u>
  <% end %>
</p>
<p>
  <b>Studet's marks:</b>
  <% if @marks.count == 0 %>
    <p> Student has not any marks yet </p>
  <% else %>
    <table border="1">
      <tr>
         <td><u>Mark</u></td>
         <td><u>Subject</u></td>
      </tr>
      <% @marks.each do |mrk| %>
        <tr>
          <td><%= mrk.mark %>
          <td><%= mrk.subject.title %>
        </tr>
      <% end %>
    </table>
  <% end %>
</p>
<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>