src/hello_world/config/routes.rb
HelloWorld::Application.routes.draw do 
  resources :faculcies

  resources :subjects

  resources :marks

  resources :students

  root :to => 'home#index'

end

src/hello_world/app/models/mark.rb
class Mark < ActiveRecord::Base
  attr_accessible :mark
  
  validates_presence_of :mark

  belongs_to :student , :inverse_of => :marks
  belongs_to :subject , :inverse_of => :marks
end

src/hello_world/app/controllers/marks_controller.rb
class MarksController < ApplicationController
  # GET /marks
  # GET /marks.json
  def index
    @marks = Mark.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @marks }
    end
  end

  # GET /marks/1
  # GET /marks/1.json
  def show
    @mark = Mark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mark }
    end
  end

  # GET /marks/new
  # GET /marks/new.json
  def new
    @mark = Mark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mark }
    end
  end

  # GET /marks/1/edit
  def edit
    @mark = Mark.find(params[:id])
  end

  # POST /marks
  # POST /marks.json
  def create
    @mark = Mark.new(params[:mark])

    respond_to do |format|
      if @mark.save
        format.html { redirect_to @mark, notice: 'Mark was successfully created.' }
        format.json { render json: @mark, status: :created, location: @mark }
      else
        format.html { render action: "new" }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /marks/1
  # PUT /marks/1.json
  def update
    @mark = Mark.find(params[:id])

    respond_to do |format|
      if @mark.update_attributes(params[:mark])
        format.html { redirect_to @mark, notice: 'Mark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.json
  def destroy
    @mark = Mark.find(params[:id])
    @mark.destroy

    respond_to do |format|
      format.html { redirect_to marks_url }
      format.json { head :no_content }
    end
  end
end

src/hello_world/app/helpers/marks_helper.rb
module MarksHelper
end

src/hello_world/app/views/marks/_form.html.erb
<%= form_for(@mark) do |f| %>
  <% if @mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
      <% @mark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mark %><br />
    <%= f.text_field :mark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/hello_world/app/views/marks/edit.html.erb
<h1>Editing mark</h1>

<%= render 'form' %>

<%= link_to 'Show', @mark %> |
<%= link_to 'Back', marks_path %>

src/hello_world/app/views/marks/index.html.erb
<h1>Listing marks</h1>

<table>
  <tr>
    <th>Mark</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @marks.each do |mark| %>
  <tr>
    <td><%= mark.mark %></td>
    <td><%= link_to 'Show', mark %></td>
    <td><%= link_to 'Edit', edit_mark_path(mark) %></td>
    <td><%= link_to 'Destroy', mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mark', new_mark_path %>

src/hello_world/app/views/marks/new.html.erb
<h1>New mark</h1>

<%= render 'form' %>

<%= link_to 'Back', marks_path %>

src/hello_world/app/views/marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mark:</b>
  <%= @mark.mark %>
</p>


<%= link_to 'Edit', edit_mark_path(@mark) %> |
<%= link_to 'Back', marks_path %>